# Generated by Django 5.2.3 on 2025-07-12 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_compatibility_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compatibility',
            name='full_name',
        ),
    ]
