# Generated by Django 5.2.3 on 2025-07-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
